
Vagrant.configure("2") do |config|

  config.vm.define "ANS-MASTER" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    #conf.vm.box = "generic/oracle8"
    conf.vm.hostname = "ans-master"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "ANS-MASTER"
      vb.memory = 1024
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/m9-Ansible-Task-01"]
      #vb.customize ["modifyvm", :id, "--nic2", "nat"]
      #vb.customize ["modifyvm", :id, "--nic2", "bridged","--bridgeadapter2", "Intel(R) 82579LM Gigabit Network Connection", "--cableconnected2", "on"]
      #vb.customize ["modifyvm", :id, "--nic2", "bridged","--bridgeadapter2", "Intel(R) Centrino(R) Advanced-N 6205", "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "internal-net"]
    end

    conf.vm.provision "file", source: "./ans-master.sh", destination: "/home/vagrant/"
    conf.vm.provision "shell", inline: <<-SHELL
    cd /home/vagrant/
    chmod +x ans-master.sh
    ./ans-master.sh
    SHELL
  end

  config.vm.define "DB-SRV1" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    #conf.vm.box = "generic/oracle8"
    conf.vm.hostname = "db-srv1"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "DB-SRV1"
      vb.memory = 1024
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/m9-Ansible-Task-01"]
      #vb.customize ["modifyvm", :id, "--nic2", "bridged","--bridgeadapter2", "Intel(R) Centrino(R) Advanced-N 6205", "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "internal-net"]
    end

    conf.vm.provision "file", source: "./db-srv.sh", destination: "/home/vagrant/"
    conf.vm.provision "shell", inline: <<-SHELL
    cd /home/vagrant/
    chmod +x db-srv.sh
    ./db-srv.sh
    SHELL
  end

  config.vm.define "WEB-SRV1" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    #conf.vm.box = "generic/oracle8"
    conf.vm.hostname = "web-srv1"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "WEB-SRV1"
      vb.memory = 1024
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/m9-Ansible-Task-01"]
      #vb.customize ["modifyvm", :id, "--nic2", "bridged","--bridgeadapter2", "Intel(R) Centrino(R) Advanced-N 6205", "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "internal-net"]
    end

    conf.vm.provision "file", source: "./web-srv.sh", destination: "/home/vagrant/"
    conf.vm.provision "shell", inline: <<-SHELL
    cd /home/vagrant/
    chmod +x web-srv.sh
    ./web-srv.sh
    SHELL
  end

  config.vm.define "WEB-SRV2" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    #conf.vm.box = "generic/oracle8"
    conf.vm.hostname = "web-srv2"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "WEB-SRV2"
      vb.memory = 1024
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/m9-Ansible-Task-01"]
      #vb.customize ["modifyvm", :id, "--nic2", "bridged","--bridgeadapter2", "Intel(R) Centrino(R) Advanced-N 6205", "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "internal-net"]
    end

     conf.vm.provision "file", source: "./web-srv2.sh", destination: "/home/vagrant/"
     conf.vm.provision "shell", inline: <<-SHELL
     cd /home/vagrant/
     chmod +x web-srv2.sh
     ./web-srv2.sh
     SHELL
  end

end
