Vagrant.configure("2") do |config|

  config.vm.define "Jenkins-Server" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    #conf.vm.box = "generic/oracle8"
    conf.vm.hostname = "jenkins"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "Jenkins-Server"
      vb.memory = 12288
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/m6-Jenkins"]
      vb.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "jenkins_internal"]
    end
    conf.vm.network "forwarded_port", guest: 2200, host: 22
    conf.vm.network "forwarded_port", guest: 80, host: 80
    conf.vm.network "forwarded_port", guest: 8080, host: 8080
    conf.vm.network "forwarded_port", guest: 9000, host: 9000
    conf.vm.provision "file", source: "./jenkins.sh", destination: "/home/vagrant/"
    conf.vm.provision "shell", inline: <<-SHELL
    cd /home/vagrant/
    chmod +x jenkins.sh
    ./jenkins.sh
    SHELL
    conf.vm.synced_folder "jenkins_vol/", "/mnt/jenkins"
  end

  config.vm.define "Node1" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    #conf.vm.box = "generic/oracle8"
    conf.vm.hostname = "node1"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "Node1"
      vb.memory = 2048
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--groups", "/m6-Jenkins"]
      vb.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "jenkins_internal"]
    end

    conf.vm.disk :disk, size: "10GB"
    conf.vm.provision "file", source: "./node.sh", destination: "/home/vagrant/"
    conf.vm.provision "shell", inline: <<-SHELL
    cd /home/vagrant/
    chmod +x node.sh
    ./node.sh
    SHELL
    conf.vm.synced_folder "node1_vol/", "/mnt/node1"
  end
end

