---
- name: Creating DB
  mysql_db:
    name: "{{db_name}}"
    state: present

- name: Creating MySQL user
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_password}}"
    priv: '*.*:ALL'
    host: '%'
    state: present
