
Vagrant.configure("2") do |config|

  config.vm.define "Rgw" do |conf|
    conf.vm.box = "generic/centos8"
    conf.vm.hostname = "rgw"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "Rgw"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--groups", "/m4-Net-Task-05"]
      vb.customize ["modifyvm", :id, "--nic2", "bridged","--bridgeadapter2", "Intel(R) Centrino(R) Advanced-N 6205", "--cableconnected2", "on"]
      vb.customize ["modifyvm", :id, "--nic3", "null"]
    end

    conf.vm.provision "file", source: "./rgw.sh", destination: "/home/vagrant/"
    conf.vm.provision "shell", inline: <<-SHELL
    cd /home/vagrant/
    chmod +x rgw.sh
    ./rgw.sh
    SHELL
  end

  config.vm.define "DHCP-DNS" do |conf|
    conf.vm.box = "generic/ubuntu2004"
    #conf.vm.box = "generic/oracle8"
    conf.vm.hostname = "dhcp-dns"
    conf.vm.box_check_update = false

    conf.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.name = "DHCP-DNS"
      vb.memory = 1536
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--groups", "/m4-Net-Task-05"]
      vb.customize ["modifyvm", :id, "--nic2", "null"]
    end

    conf.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install isc-dhcp-server -y
    SHELL
  end

end
